Add batch check support.
Li4n0/revsuit pull request #37
Opened 2021-12-16 02:52 UTC by whwlsfb

2021-12-24 11:49 UTC, wuhan005 requested changes

2021-12-24 11:49 UTC, wuhan005 commented on pkg/dns/record.go
> +		})
请求响应后函数应返回。
```suggestion
		})
		return
```

2021-12-24 11:49 UTC, wuhan005 commented on pkg/dns/record.go
> +	for i := 0; i < len(domains.Domains); i++ {
这里改成
```
for _, domain := range domains.Domains {
```
会不会更好些？

2021-12-24 11:49 UTC, wuhan005 commented on pkg/dns/record.go
> +		if err := db.Where("domain like ?", "%"+domain+"%").Count(&count); err != nil {
```suggestion
		if err := db.Where("domain like ?", "%"+domain+"%").Count(&count).Error; err != nil {
```
以及下面的 append 是不是应该放在 `err == nil`，即数据库查询没有错误的时候执行？`err != nil` 时 `count` 始终为零值 0

2021-12-24 11:49 UTC, wuhan005 commented on pkg/dns/record.go
> +		count     int64
`count` 的定义可以放到下面 L67 挨着数据库查询的地方，会更清晰一些。你觉得呢？

2021-12-24 11:49 UTC, wuhan005 commented on pkg/dns/record.go
> +		if err := db.Where("domain like ?", "%"+domain+"%").Count(&count); err != nil {
这里直接链式调用是不是更简洁一些？以及 dnsRecord 变量也可以直接改成字面量。
```go
database.DB.Model(&Record{}).Where("domain like ?", "%"+domain+"%").Count(&count)
```

2021-12-24 11:49 UTC, wuhan005 commented on pkg/rmi/record.go
> +func FindRmis(c *gin.Context) {
这边同上。

2021-12-24 11:49 UTC, wuhan005 commented on pkg/server/router.go
> +	dnsGroup.POST("batchFind", dns.FindDomains)
```suggestion
	dnsGroup.POST("/batchFind", dns.FindDomains)
```

2021-12-24 11:49 UTC, wuhan005 commented on pkg/server/router.go
> +	rmiGroup.POST("batchFind", rmi.FindRmis)
```suggestion
	rmiGroup.POST("/batchFind", rmi.FindRmis)
```

2021-12-24 12:56 UTC, Li4n0 commented
原谅我没有理解加这个功能的需求是什么.... @whwlsfb  是否方便描述下呢？

2021-12-24 13:55 UTC, whwlsfb commented
> 原谅我没有理解加这个功能的需求是什么.... @whwlsfb 是否方便描述下呢？

是我的一个log4j的扫描插件，它需要发送大量的包含唯一性的dnslog payload。如果在没有这个接口的情况下，确认dnslog是否成功反射只能挨个搜索，通过这个接口，对接我那个插件可以实现批量搜索功能。

2021-12-24 13:56 UTC, whwlsfb commented on pkg/server/router.go
> +	rmiGroup.POST("batchFind", rmi.FindRmis)
🙏 感谢大佬指教，我go语言用的不多，代码写得有点混乱，实在抱歉

2021-12-24 14:00 UTC, whwlsfb commented
@wuhan005 感谢指教，我go语言用的比较少，写的比较混乱，非常抱歉🙏

2022-01-07 14:48 UTC, Li4n0 commented
后面会考虑通过其他方式实现该功能

2022-01-07 14:48 UTC, closed without merging